name: setup astral rye

description: This action sets up Rye (astral-sh/rye) for use in actions.
author: '@mai0313'
branding:
  icon: arrow-down
  color: green

inputs:
  version:
    description: 'The version of Rye to install'
    required: false
    default: 'latest'

  toolchain_version:
    description: 'The version of the Rye toolchain to install'
    required: false
    default: '3.10'

  python_version:
    description: 'The version of Python to use'
    required: false
    default: '3.10'

  use-uv:
    description: behavior use use
    required: false
    default: 'true'

  pypi_source:
    description: 'The source of Pypi'
    required: false
    default: 'https://pypi.org/simple'

  http_proxy:
    description: 'The http proxy to use'
    required: false

  https_proxy:
    description: 'The https proxy to use'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Rye on Linux
      if: runner.os == 'Linux'
      shell: bash
      env:
        RYE_VERSION: ${{ inputs.version }}
        RYE_INSTALL_OPTION: '--yes'
        RYE_TOOLCHAIN_VERSION: ${{ inputs.toolchain_version }}
        HTTP_PROXY: ${{ inputs.http_proxy }}
        HTTPS_PROXY: ${{ inputs.https_proxy }}
        USE_UV: ${{ inputs.use-uv }}
        PYPI_SOURCE: ${{ inputs.pypi_source }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/scripts/install_ubuntu.sh
        $GITHUB_ACTION_PATH/scripts/install_ubuntu.sh

    - name: Install Rye on macOS
      if: runner.os == 'macOS'
      shell: bash
      env:
        RYE_VERSION: ${{ inputs.version }}
        RYE_INSTALL_OPTION: '--yes'
        RYE_TOOLCHAIN_VERSION: ${{ inputs.toolchain_version }}
        HTTP_PROXY: ${{ inputs.http_proxy }}
        HTTPS_PROXY: ${{ inputs.https_proxy }}
        USE_UV: ${{ inputs.use-uv }}
        PYPI_SOURCE: ${{ inputs.pypi_source }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/scripts/install_macos.sh
        $GITHUB_ACTION_PATH/scripts/install_macos.sh

    - name: Install Rye on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        RYE_VERSION: 0.39.0
        RYE_INSTALL_OPTION: '--yes'
        RYE_TOOLCHAIN_VERSION: ${{ inputs.toolchain_version }}
        HTTP_PROXY: ${{ inputs.http_proxy }}
        HTTPS_PROXY: ${{ inputs.https_proxy }}
        USE_UV: ${{ inputs.use-uv }}
        PYPI_SOURCE: ${{ inputs.pypi_source }}
      run: |
        & "$env:GITHUB_ACTION_PATH\scripts\install_windows.ps1"
