name: setup rye

on:
  push:
    branches:
      - master

jobs:
  setup-rye:
    name: Setup Rye
    runs-on: ubuntu-latest

    steps:
      - name: Setup Rye
        uses: mai0313/setup-rye@master
        with:
          version: latest
          toolchain_version: '3.10'
          python_version: '3.10'
          use-uv: true
          pypi_source: 'https://pypi.org/simple'

      - name: Check Version
        run: |
          rye --version
