name: setup rye

on:
  push:
    branches:
      - master

jobs:
  setup-rye:
    name: Setup Rye
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rye and Copy Config
        uses: mai0313/setup-rye@v1.0.1
        with:
          version: latest
          toolchain_version: '3.10'
          python_version: '3.10'
          use-uv: true
          pypi_source: 'https://pypi.org/simple'

      - name: Check Version
        run: |
          rye --version
